### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by aaronjanse** [flicaflow/julia_flake#1]
I've wanted to try Julia for a year, but I haven't been able to build the nixpkgs version.

I found this repo via GitHub search, and it *just works!* It felt great to just run `nix shell github:flicaflow/julia_flake#julia` and get exactly what I needed. I look forward to trying the packaging function, too.

Thank you!

(feel free to close this issue; I chose to thank you here since I didn't see an email in your github profile)

**Comment by flicaflow** [comment]
Thanks for the nice words, I'm happy that this helps someone. 
Just be aware that this is currently just a proof of concept and I don't know if the concept is good. The buildJulia15Package function is inspired by buildGoModule which is in nixpkgs, however I think it is not the preferred way of packaging dependencies.
Let's hope that the julia build is fixed in nixpkgs at some point, fixing it is a bit above my pay grade ;) this is merely patching the precompiled binary.

Cheers!

**Comment by flicaflow** [comment]
I steal your one liner for the readme ;)
